/*
 * Rutoken PKCS #11 extension ABI.
 *
 * This is an independent declaration of the public ABI from rtPKCS11ECP
 * 2.19.0.0.  Applications still use the vendor headers; OpenSC only needs
 * matching types and function-table order to proxy the extension.
 */

#ifndef OPENSC_PKCS11_RUTOKEN_H
#define OPENSC_PKCS11_RUTOKEN_H

#include "pkcs11.h"

#ifdef _WIN32
#pragma pack(push, rutoken, 1)
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct CK_TOKEN_INFO_EXTENDED {
	CK_ULONG ulSizeofThisStructure;
	CK_ULONG ulTokenType;
	CK_ULONG ulProtocolNumber;
	CK_ULONG ulMicrocodeNumber;
	CK_ULONG ulOrderNumber;
	CK_FLAGS flags;
	CK_ULONG ulMaxAdminPinLen;
	CK_ULONG ulMinAdminPinLen;
	CK_ULONG ulMaxUserPinLen;
	CK_ULONG ulMinUserPinLen;
	CK_ULONG ulMaxAdminRetryCount;
	CK_ULONG ulAdminRetryCountLeft;
	CK_ULONG ulMaxUserRetryCount;
	CK_ULONG ulUserRetryCountLeft;
	CK_BYTE serialNumber[8];
	CK_ULONG ulTotalMemory;
	CK_ULONG ulFreeMemory;
	CK_BYTE ATR[64];
	CK_ULONG ulATRLen;
	CK_ULONG ulTokenClass;
	CK_ULONG ulBatteryVoltage;
	CK_ULONG ulBodyColor;
	CK_ULONG ulFirmwareChecksum;
	CK_ULONG ulBatteryPercentage;
	CK_ULONG ulBatteryFlags;
} CK_TOKEN_INFO_EXTENDED;
typedef CK_TOKEN_INFO_EXTENDED *CK_TOKEN_INFO_EXTENDED_PTR;

#define TOKEN_TYPE_UNKNOWN                       0xFFUL
#define TOKEN_CLASS_UNKNOWN                      0xFFFFFFFFUL
#define TOKEN_FLAGS_ADMIN_CHANGE_USER_PIN        0x00000001UL
#define TOKEN_FLAGS_USER_CHANGE_USER_PIN         0x00000002UL
#define TOKEN_FLAGS_ADMIN_PIN_NOT_DEFAULT        0x00000004UL
#define TOKEN_FLAGS_USER_PIN_NOT_DEFAULT         0x00000008UL
#define TOKEN_FLAGS_SUPPORT_FKC                  0x00000010UL
#define TOKEN_FLAGS_HAS_FLASH_DRIVE              0x00000080UL
#define TOKEN_FLAGS_SUPPORT_SECURE_MESSAGING     0x00000100UL
#define TOKEN_FLAGS_HAS_BUTTON                   0x00000200UL
#define TOKEN_FLAGS_SUPPORT_JOURNAL              0x00000400UL
#define TOKEN_FLAGS_USER_PIN_UTF8                0x00000800UL
#define TOKEN_FLAGS_ADMIN_PIN_UTF8               0x00001000UL

typedef struct CK_RUTOKEN_INIT_PARAM CK_RUTOKEN_INIT_PARAM;
typedef CK_RUTOKEN_INIT_PARAM *CK_RUTOKEN_INIT_PARAM_PTR;
typedef CK_ULONG CK_VOLUME_ID_EXTENDED;
typedef CK_ULONG CK_ACCESS_MODE_EXTENDED;
typedef struct CK_VOLUME_INFO_EXTENDED CK_VOLUME_INFO_EXTENDED;
typedef CK_VOLUME_INFO_EXTENDED *CK_VOLUME_INFO_EXTENDED_PTR;
typedef struct CK_VOLUME_FORMAT_INFO_EXTENDED CK_VOLUME_FORMAT_INFO_EXTENDED;
typedef CK_VOLUME_FORMAT_INFO_EXTENDED *CK_VOLUME_FORMAT_INFO_EXTENDED_PTR;
typedef struct CK_VENDOR_BUFFER CK_VENDOR_BUFFER;
typedef CK_VENDOR_BUFFER *CK_VENDOR_BUFFER_PTR;
typedef CK_VENDOR_BUFFER_PTR *CK_VENDOR_BUFFER_PTR_PTR;
typedef struct CK_VENDOR_X509_STORE CK_VENDOR_X509_STORE;
typedef CK_VENDOR_X509_STORE *CK_VENDOR_X509_STORE_PTR;
typedef CK_ULONG CK_VENDOR_CRL_MODE;
typedef CK_BYTE_PTR *CK_BYTE_PTR_PTR;

typedef struct CK_FUNCTION_LIST_EXTENDED CK_FUNCTION_LIST_EXTENDED;
typedef CK_FUNCTION_LIST_EXTENDED *CK_FUNCTION_LIST_EXTENDED_PTR;
typedef CK_FUNCTION_LIST_EXTENDED_PTR *CK_FUNCTION_LIST_EXTENDED_PTR_PTR;

#define CK_RUTOKEN_FUNCTION(name, args) typedef CK_RV (*CK_ ## name) args

CK_RUTOKEN_FUNCTION(C_EX_GetFunctionListExtended,
		(CK_FUNCTION_LIST_EXTENDED_PTR_PTR));
CK_RUTOKEN_FUNCTION(C_EX_InitToken,
		(CK_SLOT_ID, CK_UTF8CHAR_PTR, CK_ULONG, CK_RUTOKEN_INIT_PARAM_PTR));
CK_RUTOKEN_FUNCTION(C_EX_GetTokenInfoExtended,
		(CK_SLOT_ID, CK_TOKEN_INFO_EXTENDED_PTR));
CK_RUTOKEN_FUNCTION(C_EX_UnblockUserPIN, (CK_SESSION_HANDLE));
CK_RUTOKEN_FUNCTION(C_EX_SetTokenName,
		(CK_SESSION_HANDLE, CK_CHAR_PTR, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_SetLicense,
		(CK_SESSION_HANDLE, CK_ULONG, CK_BYTE_PTR, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_GetLicense,
		(CK_SESSION_HANDLE, CK_ULONG, CK_BYTE_PTR, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_GetCertificateInfoText,
		(CK_SESSION_HANDLE, CK_OBJECT_HANDLE, CK_CHAR_PTR *, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_PKCS7Sign,
		(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_OBJECT_HANDLE,
		 CK_BYTE_PTR *, CK_ULONG_PTR, CK_OBJECT_HANDLE,
		 CK_OBJECT_HANDLE_PTR, CK_ULONG, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_CreateCSR,
		(CK_SESSION_HANDLE, CK_OBJECT_HANDLE, CK_CHAR_PTR *, CK_ULONG,
		 CK_BYTE_PTR *, CK_ULONG_PTR, CK_OBJECT_HANDLE, CK_CHAR_PTR *,
		 CK_ULONG, CK_CHAR_PTR *, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_FreeBuffer, (CK_BYTE_PTR));
CK_RUTOKEN_FUNCTION(C_EX_GetTokenName,
		(CK_SESSION_HANDLE, CK_CHAR_PTR, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_SetLocalPIN,
		(CK_SLOT_ID, CK_UTF8CHAR_PTR, CK_ULONG, CK_UTF8CHAR_PTR,
		 CK_ULONG, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_LoadActivationKey,
		(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_SetActivationPassword,
		(CK_SLOT_ID, CK_UTF8CHAR_PTR));
CK_RUTOKEN_FUNCTION(C_EX_GetVolumesInfo,
		(CK_SLOT_ID, CK_VOLUME_INFO_EXTENDED_PTR, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_GetDriveSize, (CK_SLOT_ID, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_ChangeVolumeAttributes,
		(CK_SLOT_ID, CK_USER_TYPE, CK_UTF8CHAR_PTR, CK_ULONG,
		 CK_VOLUME_ID_EXTENDED, CK_ACCESS_MODE_EXTENDED, CK_BBOOL));
CK_RUTOKEN_FUNCTION(C_EX_FormatDrive,
		(CK_SLOT_ID, CK_USER_TYPE, CK_UTF8CHAR_PTR, CK_ULONG,
		 CK_VOLUME_FORMAT_INFO_EXTENDED_PTR, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_TokenManage,
		(CK_SESSION_HANDLE, CK_ULONG, CK_VOID_PTR));
CK_RUTOKEN_FUNCTION(C_EX_GenerateActivationPassword,
		(CK_SESSION_HANDLE, CK_ULONG, CK_UTF8CHAR_PTR, CK_ULONG_PTR,
		 CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_GetJournal,
		(CK_SLOT_ID, CK_BYTE_PTR, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_SignInvisibleInit,
		(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE));
CK_RUTOKEN_FUNCTION(C_EX_SignInvisible,
		(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG, CK_BYTE_PTR,
		 CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_SlotManage,
		(CK_SLOT_ID, CK_ULONG, CK_VOID_PTR));
CK_RUTOKEN_FUNCTION(C_EX_WrapKey,
		(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_ATTRIBUTE_PTR, CK_ULONG,
		 CK_MECHANISM_PTR, CK_OBJECT_HANDLE, CK_MECHANISM_PTR,
		 CK_BYTE_PTR, CK_ULONG_PTR, CK_OBJECT_HANDLE_PTR));
CK_RUTOKEN_FUNCTION(C_EX_UnwrapKey,
		(CK_SESSION_HANDLE, CK_MECHANISM_PTR, CK_OBJECT_HANDLE,
		 CK_MECHANISM_PTR, CK_BYTE_PTR, CK_ULONG, CK_ATTRIBUTE_PTR,
		 CK_ULONG, CK_OBJECT_HANDLE_PTR));
CK_RUTOKEN_FUNCTION(C_EX_PKCS7VerifyInit,
		(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG,
		 CK_VENDOR_X509_STORE_PTR, CK_VENDOR_CRL_MODE, CK_FLAGS));
CK_RUTOKEN_FUNCTION(C_EX_PKCS7Verify,
		(CK_SESSION_HANDLE, CK_BYTE_PTR_PTR, CK_ULONG_PTR,
		 CK_VENDOR_BUFFER_PTR_PTR, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_PKCS7VerifyUpdate,
		(CK_SESSION_HANDLE, CK_BYTE_PTR, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_PKCS7VerifyFinal,
		(CK_SESSION_HANDLE, CK_VENDOR_BUFFER_PTR_PTR, CK_ULONG_PTR));
CK_RUTOKEN_FUNCTION(C_EX_Authenticate,
		(CK_SESSION_HANDLE, CK_OBJECT_HANDLE, CK_BYTE_PTR, CK_ULONG));
CK_RUTOKEN_FUNCTION(C_EX_Deauthenticate,
		(CK_SESSION_HANDLE, CK_OBJECT_HANDLE));
CK_RUTOKEN_FUNCTION(C_EX_UnblockAuthenticator,
		(CK_SESSION_HANDLE, CK_OBJECT_HANDLE));

#undef CK_RUTOKEN_FUNCTION

struct CK_FUNCTION_LIST_EXTENDED {
	CK_VERSION version;
	CK_C_EX_GetFunctionListExtended C_EX_GetFunctionListExtended;
	CK_C_EX_InitToken C_EX_InitToken;
	CK_C_EX_GetTokenInfoExtended C_EX_GetTokenInfoExtended;
	CK_C_EX_UnblockUserPIN C_EX_UnblockUserPIN;
	CK_C_EX_SetTokenName C_EX_SetTokenName;
	CK_C_EX_SetLicense C_EX_SetLicense;
	CK_C_EX_GetLicense C_EX_GetLicense;
	CK_C_EX_GetCertificateInfoText C_EX_GetCertificateInfoText;
	CK_C_EX_PKCS7Sign C_EX_PKCS7Sign;
	CK_C_EX_CreateCSR C_EX_CreateCSR;
	CK_C_EX_FreeBuffer C_EX_FreeBuffer;
	CK_C_EX_GetTokenName C_EX_GetTokenName;
	CK_C_EX_SetLocalPIN C_EX_SetLocalPIN;
	CK_C_EX_LoadActivationKey C_EX_LoadActivationKey;
	CK_C_EX_SetActivationPassword C_EX_SetActivationPassword;
	CK_C_EX_GetVolumesInfo C_EX_GetVolumesInfo;
	CK_C_EX_GetDriveSize C_EX_GetDriveSize;
	CK_C_EX_ChangeVolumeAttributes C_EX_ChangeVolumeAttributes;
	CK_C_EX_FormatDrive C_EX_FormatDrive;
	CK_C_EX_TokenManage C_EX_TokenManage;
	CK_C_EX_GenerateActivationPassword C_EX_GenerateActivationPassword;
	CK_C_EX_GetJournal C_EX_GetJournal;
	CK_C_EX_SignInvisibleInit C_EX_SignInvisibleInit;
	CK_C_EX_SignInvisible C_EX_SignInvisible;
	CK_C_EX_SlotManage C_EX_SlotManage;
	CK_C_EX_WrapKey C_EX_WrapKey;
	CK_C_EX_UnwrapKey C_EX_UnwrapKey;
	CK_C_EX_PKCS7VerifyInit C_EX_PKCS7VerifyInit;
	CK_C_EX_PKCS7Verify C_EX_PKCS7Verify;
	CK_C_EX_PKCS7VerifyUpdate C_EX_PKCS7VerifyUpdate;
	CK_C_EX_PKCS7VerifyFinal C_EX_PKCS7VerifyFinal;
	CK_C_EX_Authenticate C_EX_Authenticate;
	CK_C_EX_Deauthenticate C_EX_Deauthenticate;
	CK_C_EX_UnblockAuthenticator C_EX_UnblockAuthenticator;
};

CK_RV CK_SPEC C_EX_GetFunctionListExtended(
		CK_FUNCTION_LIST_EXTENDED_PTR_PTR ppFunctionList);

#ifdef __cplusplus
}
#endif

#ifdef _WIN32
#pragma pack(pop, rutoken)
#endif

#endif
